version: '2'
services:
    task1:
        build: ./task1
        ports:
            - "5000:5000"
    task2:
        build: ./task2
        ports:
            - "5001:5001"
    task3:
        build: ./task3
        ports:
            - "5002:5002"
        depends_on:
            - db
    db:
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=magic3_db
        expose:
            - "5432"